config/routes.rb
Rails.application.routes.draw do
  root to: "homes#home"
  get '/auth/github/callback', to: 'sessions#github'
  get '/sign_out', to: 'sessions#destroy'
  resources :hobbies, only: [:index, :show, :new, :create] do
    resources :tasks, except: :index
  end
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :hobby
  validates :task_name, presence: true
  validates :hobby_id, presence: true
  validates :complete, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hobbies

  def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

    find_or_create_by(provider: provider, uid: uid) do |user|
      user.provider = provider
      user.uid = uid
      user.email = auth.info.email
      user.username = auth.info.name
      user.avatar_url = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :correct_user,   only: [:index, :show]
  before_action :logged_in_user, only: [:index, :show]

  def index
    @user = User.find_by(id: session[:user_id])
    @hobbies = Hobby.where(user_id: session[:user_id])
  end

  def show
    @hobby = Hobby.find(params[:id])
    @tasks = @hobby.tasks
    @hobbies = Hobby.where(user_id: session[:user_id])
  end

  def new
    @hobby = Hobby.new
    @hobbies = Hobby.where(user_id: session[:user_id])
  end

  def create
    @hobby = Hobby.new(hobby_params)
    @hobby.user_id = session[:user_id]
    if @hobby.save
      flash.notice = "Hobby added successfully"
      redirect_to hobbies_path
    else
      flash.notice = @hobby.errors.full_messages.join(". ")
      render "new"
    end
  end

  private
  def hobby_params
    params.require(:hobby).permit(
    :name,
    :description
    )
  end


  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to root_url
    end
  end

  def correct_user
    @user = User.find_by(id: session[:user_id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def github
    @user = User.find_or_create_from_omniauth(auth_hash)
    session[:user_id] = @user.id
    flash.notice = "You are now signed in as #{@user.username}!"
    redirect_to hobbies_path
  end

  def destroy
    session[:user_id] = nil
    flash.notice = "You have been signed out"
    redirect_to "/"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @hobbies = Hobby.where(user_id: session[:user_id])
    @hobby = Hobby.find(params[:hobby_id])
    @task = Task.find(params[:id])
  end

  def new
    @hobbies = Hobby.where(user_id: session[:user_id])
    @hobby = Hobby.find(params[:hobby_id])
    @task = Task.new
  end

  def create
    @hobby = Hobby.find(params[:hobby_id])
    @task = Task.new(task_params)
    @task.hobby = @hobby
    if @task.save
      flash.notice = "Task added successfully"
      redirect_to hobby_path(@hobby)
    else
      flash.notice = @task.errors.full_messages.join(". ")
      render "new"
    end
  end

  private
  def task_params
    params.require(:task).permit(
    :task_name,
    :description,
    :link,
    :complete
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_boards
    @boards ||= Board.where(user_id: session[:user_id])
  end
end

app/views/hobbies/index.html.erb
<div class="full-height bg-img">
<div class="row">
  <div class="small-12 medium-10 medium-centered large-8 large-centered columns">

    <div class="floating-container">
      <h1>Passions</h1>
    </div>
      <% @hobbies.each do |hobby| %>
      <div class="floating-container">
        </h4><%= link_to hobby.name, hobby_path(hobby) %></h4>
      </div>
      <% end %>
    <div class="text-center">
      <a href="<%= new_hobby_path %>" class="button">Add a New Hobby!</a>
    </div>
  </div>
</div>
</div>

app/views/hobbies/new.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered large-8 large-centered columns">
    <h1>New Hobby Form</h1>

    <%= form_for(@hobby) do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/hobbies/show.html.erb
<div class="row">
  <div class="small-12 columns">

    <div class="floating-container text-center small-12 medium-10 medium-centered large-8 large-centered columns">
      <h1><%= @hobby.name %></h1>
      <p><%= @hobby.description %></p>
    </div>

    <% @tasks.each do |task| %>
    <div class="floating-container small-12 medium-10 medium-centered large-8 large-centered columns">
      <h4 class="name"><%= task.task_name %></h4>
      <p><%= task.description %></p>
      <% unless task.link.nil? || task.link.strip.empty? %>
      <div class="video-container">
        <iframe id="player" type="text/html" width="640" height="390" src="<%= task.link.gsub(/((https?:\/\/)?(www.)?youtube.com\/watch\?v=)/i, "https://www.youtube.com/embed/") %>" frameborder="0"></iframe>
      </div>
      <% end %>
    </div>
    <% end %>

    <div class="text-center ">
      <a href="<%= new_hobby_task_path(@hobby) %>" class="button">Add a Challenge</a>
      <a href="<%= hobbies_path %>" class="button">Your Hobbies</a>
    </div>
  </div>
</div>

app/views/homes/home.html.erb
<div id="top" class="full-height home text-center">
  <div class="bg row">
    <div class="small-8 small-offset-2 shadow columns">
      <h1 class="title">Passion Craze</h1>
      <h3>Let's share and discover our passions<h3>
      <% if current_user %>
        <a href="/hobbies" class="button">Your Passions</a>
      <% else %>
        <a href="/auth/github" class="button">Log in!</a>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Passion Craze" %></title>

  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script|Volkhov' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1 class="title"><%= link_to "Passion Craze", root_path %></h1>
        </li>

        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <ul class="left">
          <li class="has-dropdown">
        <%= link_to "Hobbies", hobbies_path %>
        <ul class="dropdown">
          <% @hobbies.each do |hobby| %>
          <li><%= link_to hobby.name, hobby_path(hobby) %></li>
          <% end %>
        </ul>
      </li>
        </ul>

        <!-- Right Nav Section -->
        <ul class="right">
          <% if current_user %>
          <li><a href="#"><%= current_user.username %></a></li>
          <!-- <li><img src="<%= current_user.avatar_url %>"></li> -->
          <li><%= link_to "Sign out", "/sign_out" %></li>
          <% else %>
          <li><%= link_to "Sign in with Github", "/auth/github" %></li>
          <% end %>
        </ul>
      </section>
    </nav>
  </div>

  <% flash.each do |key, value| %>
  <%= value %>
  <% end %>
  <%= yield %>

  <script>
  $(document).foundation();
  $(".full-height").height($(".main").parent().height());
  </script>
  <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>
    <script>
      $(document).foundation({
        accordion: {
          callback : function (accordion) {
            console.log(accordion);
          }
        }
      });
    </script>

</body>
</html>

app/views/tasks/new.html.erb
<div class="row">
  <div class="small-12 medium-10 medium-centered large-8 large-centered columns">
    <h1>New Task</h1>

    <%= form_for [@hobby, @task] do |f| %>
    <div>
      <%= f.label :task_name %>
      <%= f.text_field :task_name %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div>
      <%= f.label :link %>
      <%= f.text_field :link %>
    </div>
    <div>
      <%= f.label :complete, "Mastered" %>
      <%= f.check_box :complete %>
    </div>
    <div>
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>